### PR TITLE
Refacto algo & Clean code

### PR DESCRIPTION
**Pull request by qmonmert**

### CODE REVIEW

**Review by nivekcode — APPROVED** [review]
Nice! That's so much better, thx a lot! 💪

**Comment by qmonmert** [comment]
🚀

**Comment by qmonmert** [comment]
> 🎉 This PR is included in version 2.0.1 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/ng-eggsplore/v/2.0.1)
> * [GitHub release](https://github.com/kreuzerk/ng-eggsplore/releases/tag/v2.0.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

👍

**Pull request merged**
